#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	/usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
	/usr/share/openstack-dashboard/manage.py compress --force
	if [ -f /var/lib/openstack-dashboard/secret-key/.secret_key_store ]; then
		rm /var/lib/openstack-dashboard/secret-key/.secret_key_store
	fi
	chown -R www-data /var/lib/openstack-dashboard/secret-key /var/lib/openstack-dashboard/static
fi

#DEBHELPER#
